import type { Player } from '../game/player'
import { createPlayer } from '../game/player'
import { trainPlayer } from '../game/training'
import { createRNG } from '../game/rng'
import { createAIPool } from '../game/ai'
import { tournaments } from '../data/tournaments'
import { canEnterTournament, runTournament, type TournamentResult } from '../game/tournament'
import { updateRankings } from '../game/ranking'
import { advanceAge } from '../game/progression'
import { recoverFromInjuries } from '../game/injury'
import { careerEvents } from '../data/events'
import { applyMonthlyTraining, applyMonthlyRest, awardAnnualPoints, type MonthlyTraining } from '../game/monthly'
export interface GameState { player: Player | null; seed: string; lastTournament: TournamentResult | null; activeEvent: string | null }
export type GameAction = { type: 'CREATE_PLAYER'; payload: { name: string; nationality?: string; handedness?: 'left' | 'right'; height?: number; weight?: number } } | { type: 'TRAIN'; payload: { category: 'technical' | 'physical' | 'mental' | 'recovery'; intensity: 'low' | 'normal' | 'high' } } | { type: 'PLAY_TOURNAMENT'; payload: { tournamentId: string } } | { type: 'MONTHLY_TRAINING'; payload: { kind: MonthlyTraining } } | { type: 'MONTHLY_REST' } | { type: 'ANNUAL_SETTLEMENT'; payload: { achievementBonus: number } } | { type: 'ADVANCE_SEASON' } | { type: 'TRIGGER_EVENT' } | { type: 'CHOOSE_EVENT'; payload: { choiceId: string } } | { type: 'RETIRE' } | { type: 'RESET' }
export const initialState: GameState = { player: null, seed: 'MALAYSIA2026', lastTournament: null, activeEvent: null }
export function gameReducer(state: GameState, action: GameAction): GameState { const p = state.player; if (action.type === 'CREATE_PLAYER') return { ...state, player: createPlayer(action.payload.name, 'all-round', action.payload.nationality ?? 'MAS', action.payload.handedness ?? 'right', action.payload.height ?? 175, action.payload.weight ?? 70) }; if (!p) return action.type === 'RESET' ? initialState : state; if (action.type === 'MONTHLY_TRAINING') return { ...state, player: applyMonthlyTraining(p, action.payload.kind) }; if (action.type === 'MONTHLY_REST') return { ...state, player: applyMonthlyRest(p) }; if (action.type === 'ANNUAL_SETTLEMENT') return { ...state, player: awardAnnualPoints(p, action.payload.achievementBonus) }; if (action.type === 'TRAIN' && !p.retired) return { ...state, player: trainPlayer(p, action.payload.category, action.payload.intensity, createRNG(`${state.seed}-${p.currentSeason}-${p.fatigue}`)) }; if (action.type === 'PLAY_TOURNAMENT' && !p.retired) { const t = tournaments.find(x => x.id === action.payload.tournamentId); if (!t || !canEnterTournament(p, t)) return state; const result = runTournament(p, createAIPool(5, createRNG(`${state.seed}-${t.id}-${p.currentSeason}`)), t, createRNG(`${state.seed}-matches-${p.currentSeason}`)); const ranked = updateRankings([result.player, ...createAIPool(20, createRNG(`${state.seed}-ranking`))]).find(x => x.id === result.player.id) ?? result.player; return { ...state, player: ranked, lastTournament: result.result } }; if (action.type === 'ADVANCE_SEASON' && !p.retired) return { ...state, player: recoverFromInjuries(advanceAge(p)), lastTournament: null }; if (action.type === 'TRIGGER_EVENT' && !p.retired) return { ...state, activeEvent: careerEvents[0]?.id ?? null }; if (action.type === 'CHOOSE_EVENT' && state.activeEvent) { const e = careerEvents.find(x => x.id === state.activeEvent); const c = e?.choices.find(x => x.id === action.payload.choiceId); return c ? { ...state, player: c.apply(p), activeEvent: null } : state }; if (action.type === 'RETIRE') return { ...state, player: { ...p, retired: true }, activeEvent: null }; if (action.type === 'RESET') return initialState; return state }
